### PR TITLE
Fix docs generation

### PR DESCRIPTION
**Pull request by Veetaha**
*Issue #, if available:*

*Description of changes:*
Fix the build failure of github ci.
Worked for me in https://github.com/Veetaha/aws-lambda-rust-runtime/actions/runs/168969975

cc @softprops, https://github.com/awslabs/aws-lambda-rust-runtime/pull/234
@davidbarsky  

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Comment by softprops** [comment]
Nice catch

**Comment by Veetaha** [comment]
Yup, made aws green again :D

**Comment by softprops** [comment]
The branch and content exist in expected shape https://github.com/awslabs/aws-lambda-rust-runtime/tree/gh-pages but I don't yet see the hosted version yet https://awslabs.github.io/aws-lambda-rust-runtime.

Anecdotally I've seen the first gh-pages build push not work the first time in other repos due to some GitHub pages quirks which registering the repos gh pages integration. 

@davidbarsky can you check the https://github.com/awslabs/aws-lambda-rust-runtime/settings to see what the gh pages section looks like. Here's an example from one of my repos 
Screen Shot 2020-07-14 at 4 10 17 PM

**Comment by davidbarsky** [comment]
@softprops Ah, thanks for the heads up. I've opted for the gh-pages branch and now the UI is showing "Your site is ready to be published at http://awslabs.github.io/aws-lambda-rust-runtime/". I'm guessing we'll need another build?

**Comment by softprops** [comment]
I think so. Any tiny change to rust docs will do I think. Any missing periods? :)

**Comment by softprops** [comment]
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token my bad. This is actually expected. There's a note about first builds here

**Comment by davidbarsky** [comment]
D'oh, thanks a bunch.

**Pull request merged**
