### PR TITLE
clean up dependencies

### PR DESCRIPTION
**Pull request by softprops**
*Issue #, if available:*

*Description of changes:*

This puts dependencies in place where they are actually used in the runtime module and removed where they aren't. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by davidbarsky** [comment]
I'll merge when Travis succeeds.

**Comment by sapessi** [comment]
Thanks @softprops - those dev dependencies are there because I had started working on a DyanmoDB example but it never made it to the repo in time. I'll add them back once I'm ready to publish the example.

**Comment by softprops** [comment]
It looks like the travis jobs are complete but no one phoned back home to github to note that. can you folks retrigger the travis build for this pull

**Comment by davidbarsky** [comment]
@softprops restarted.

**Comment by softprops** [comment]
👍

**Pull request merged**
