### PR TITLE
add parity to the lambda macro to support handler closure impl

### PR DESCRIPTION
**Pull request by softprops**
*Issue #, if available:*

*Description of changes:*

This is a follow up to #19 to add support for the new closure style handlers with the `lambda!` macro. I made attempt to hit to birds (docs and tests) with on doctest coverage.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by davidbarsky** [comment]
This looks great, thank you!

**Comment by davidbarsky** [comment]
Ugh, can you resolve the merge issues? Sorry about that.

**Comment by softprops** [comment]
yep

**Comment by softprops** [comment]
updated

**Pull request merged**
