### PR TITLE
Merge Conflicts for PR 'Error logging and examples'

### PR DESCRIPTION
**Pull request by bahildebrand**
Issue #, if available: #242 

Description of changes:
This PR is a continuation of #242. It solves the merge conflicts present from the branch becoming stale, and adds no new content. A new PR was created because we did not get a response from the owner of PR #242, and we did not have permissions to edit his branch. Credit to @rimutaka for the changes.

By submitting this pull request

- [*] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [*] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Review by coltonweaver — APPROVED** [review]
These look good to me.

**Comment by vultix** [comment]
@coltonweaver @rimutaka Is there a reason Send + Sync requirements were added?  Sync is a restrictive requirement and breaks all of our lambdas using any of these:
- Rusoto
- Mongodb
- Sqlx

This is the commit: [Enforced Send+Sync for http Handler impl.](https://github.com/awslabs/aws-lambda-rust-runtime/pull/284/commits/166d63848419639c5c30ad3c263781613f8f9341)

**Comment by bahildebrand** [comment]
@vultix, what is failing exactly. Are you unable to pass in clients for those libraries to the invocations from the base lambda instance?

**Comment by vultix** [comment]
@bahildebrand Here's a simple example.  Note that normal lambdas work, it's only the http lambdas that have started failing:

```rust
use lambda_http::{
    handler,
    lambda::{self, Context},
    IntoResponse, Request, RequestExt, Response,
};

use serde_json::{json, Value};
use rusoto_core::Region;
use rusoto_dynamodb::{DynamoDb, DynamoDbClient, ListTablesInput};

type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda::run(handler(func)).await?;
    Ok(())
}

async fn func(_: Request, _: Context) -> Result<Value, Error> {
    let client = DynamoDbClient::new(Region::UsEast1);

    let output = client.list_tables(Default::default()).await?;

    dbg!{output};

    Ok(json!({"success": true}))
}
```

```toml
[dependencies]
serde_json = "1.0"
serde = "1.0"
tokio = {version = "1.0", features = ["macros"]}

lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
rusoto_dynamodb = "0.46.0"
rusoto_core = "0.46.0"
```

This is the error I get: 
```
error: future cannot be shared between threads safely
   --> src/main.rs:16:17
    |
16  |     lambda::run(handler(func)).await?;
    |                 ^^^^^^^ future returned by `func` is not `Sync`
    | 
   ::: ~/.cargo/git/checkouts/aws-lambda-rust-runtime-7c865cce90132439/9bd45c1/lambda-http/src/lib.rs:109:19
    |
109 | pub fn handler<H: Handler>(handler: H) -> Adapter<H> {
    |                   ------- required by this bound in `handler`
    |
    = help: the trait `Sync` is not implemented for `dyn Future<Output = std::result::Result<ListTablesOutput, RusotoError<ListTablesError>>> + Send`
note: future is not `Sync` as it awaits another future which is not `Sync`
   --> src/main.rs:23:18
    |
23  |     let output = client.list_tables(Default::default()).await?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here on type `Pin<Box<dyn Future<Output = std::result::Result<ListTablesOutput, RusotoError<ListTablesError>>> + Send>>`, which is not `Sync`

```

You get similar `'Sync' is not implemented` errors when doing simple operations using mongodb and sqlx as well.   If you pin lambda and lambda_http to a revision before this PR everything compiles.

**Comment by bahildebrand** [comment]
@vultix Would you mind opening an issue for this so I can track it there? I'm going to take a look at this for you.

**Comment by vultix** [comment]
@bahildebrand I created Issue #287

**Pull request merged**
