### PR TITLE
add docs.rs badges

### LINKED ISSUE #52: docs.rs badge placement
docs.rs makes it easy to host your rustdocs for free https://docs.rs/lambda_runtime/0.1.0/lambda_runtime/  it also offers a quality of life feature with its [badge urls](https://docs.rs/lambda_runtime/badge.svg) Since there's one central readme for this project (with a list of modules and descriptions at the top) it make make sense to add a badge for each there I wanted to open up an issue for discussion first

### PR DESCRIPTION
**Pull request by softprops**
*Issue #, if available:*

fixes #52 

*Description of changes:*

Added [docs.rs badges](https://docs.rs/about) to README to make documentation more discoverable 

By submitting this pull request

- [X] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [X] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Comment by softprops** [comment]
this change is best reviewed by clicking the "view file" button in the files changed listing. github renders the markdown so you can get a better sense for the visual effect of the rendered markdown

**Comment by softprops** [comment]
thoughts on crates.io badges as well in addition to docs.rs badges? they serve different purposes but are roughly the same level of effort to add?

**Comment by davidbarsky** [comment]
@softprops yeah, I like the docs.rs badge! LGTM.

**Comment by softprops** [comment]
@davidbarsky thoughts on crates.io badges as well?

**Comment by davidbarsky** [comment]
@softprops yeah let's do it

**Pull request merged**
