### PR TITLE
Typo in JSON serialization error message.

### PR DESCRIPTION
**Pull request by alex-ozdemir**
I stumbled upon a small typo while reading the source.

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Comment by davidbarsky** [comment]
Thanks for opening this PR! This change looks good to me—I'll try to see why the build is failing on nightly, while it's succeeding on stable.

**Comment by alex-ozdemir** [comment]
This failure is actually unrelated to this PR.

A few days ago the doc-dude, Giullaume landed [this](https://github.com/rust-lang/rust/pull/56407) PR, which made the `missing_docs` warning stop ignoring `macro_rules` macro definitions. Since y'all have `#[deny(warnings)]` on in the `lambda-runtime` crate, and [this macro](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/runtime.rs#L48) is missing documentation, this caused the build to fail on nightly. 

I've added documentation for that macro in [this PR](https://github.com/awslabs/aws-lambda-rust-runtime/pull/71).

**Comment by davidbarsky** [comment]
> This failure is actually unrelated to this PR.

Yep, you're right! I meant to say “investigate what happened in `rustc`”, but thanks for doing that research for me!

**Comment by davidbarsky** [comment]
Once #71 is merged, I'll restart this build—I don't think that a rebase is necessary. Thanks for your help!

**Comment by davidbarsky** [comment]
Thanks! Just merged these changes. Also, I'm sorry about the delay! I'll ask the administrators of the `awslabs` organization if email notifications can be turned on.

**Pull request merged**
