### PR TITLE
Have TravisCI cache cargo between builds.

### PR DESCRIPTION
**Pull request by davidbarsky**
*Description of changes:*

see title.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by softprops** [comment]
You may want to keep in mind some of the caveats identied of this approach listed in [this post](https://levans.fr/rust_travis_cache.html)

**Comment by davidbarsky** [comment]
Thanks @softprops! That motivated me to not have the the cache initially, but then I noticed Travis took ~30 minutes to run, whereas other projects I worked on (Tokio Trace, for one) took _maybe_ 2 minutes. The only difference was the presence of cached Travis CI. I’m open to re-evaluating this choice, however!

**Comment by davidbarsky** [comment]
Hmm, the issue seems to be related to the fact that we're building for macOS. It might make sense to skip, IMO.

**Comment by sapessi** [comment]
Yeah. No need to build for macos

**Comment by softprops** [comment]
It's not about not caching but what to cache. There's some notes in the post on more focused dirs to cache.

**Comment by davidbarsky** [comment]
Thanks @softprops. I've added the caching strategy that the article recommended.

**Pull request merged**
